server:
  port: '{cipher}http://localhost:8090/orderclient-dev.yml' 
user.userInfo.path: http://localhost:8080/u/{id}
spring:
  application:
    name: orderclient
  datasource: 
    username: dbuser1
    password: '{cipher}04caadb136344d641912968564168c1289a81aa6c00720be2e8239a1ab938096'
eureka: 
  client: 
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/,http://user:password123@localhost:8762/eureka/
feign: 
  hystrix: 
    enabled: true
management:
  security:
    enabled: false