server:
  port: 8003
#userservice: 
#  ribbon: 
#    ribbonLoadBalancer: com.netflix.loadbalancer.ZoneAwareLoadBalancer  
user.userInfo.path: http://localhost:8080/u/{id}
spring:
  application:
    name: orderclient
eureka: 
  client: 
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/,http://user:password123@localhost:8762/eureka/
feign: 
  hystrix: 
    enabled: true
management:
  security:
    enabled: false
spring:
  datasource:
    username: dbuser
    password: 'AQAwtqMocSUrfKutUMhh5NEKtNhZVHQ5ptvDUjMB/pPfw4f9+7RYsybUY/vHY8k1o5lNweZQ6fgQNv/TJqp7ZGWs26X9C07OVDCjKxr+HBUUHMoc9GsphXJdQOXhrxw4dvCHPGFZ061RI84vecezWHjCyEWIL9RyypT9zeCR7+vbBDEKr9BEdsV2WnHbtjRzKdLHTWstSYTZ+gXpTQMY7Hh1zlf19PXeVYI+WEybp9fdkwjTRji268nPZkBL42iKkG7WBAeHETBVjN0jNqYFT+r7PZjqIN82MAqMjjfN0EyZje783zDCXe3XZUPMCS1HY3yDDtwBFL8+jDcIcGbTO6/D1+eMCxNAZmd3G3IBETdNYgCdI02IVEUpPaZAc1Z+j9o='        